# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# -*- encoding: utf-8 -*-
$:.push(File.expand_path('../lib', __FILE__))
require('paranoid/version')

Gem::Specification.new do |s|
  s.name        = 'paranoid_create'
  s.version     = Paranoid::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ['Philipp Ullmann']
  s.email       = 'philipp.ullmann@create.at'
  s.homepage    = 'http://github.com/create-philipp-ullmann/paranoid/'
  s.summary     = 'Enable soft delete of ActiveRecord records. Based off defunct ActsAsParanoid and IsParanoid'

  s.rubyforge_project = 'paranoid_create'

  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  s.require_paths = ['lib']
  
  s.add_development_dependency('rspec', ['>= 2.5.0'])
  s.add_development_dependency('sqlite3-ruby', ['>= 1.3.3'])
  s.add_development_dependency('activerecord', ['>= 3.0.5'])
end
